### ISSUE TITLE
ipod-touch-2g doesnt launch 

### ISSUE THREAD

**Issue by nanocodium** [devos50/qemu#96] opened 2023-12-15 22:06 UTC
boot command: 
./qemu-system-arm.exe -M iPod-Touch,bootrom="/c/Users/nano/Downloads/qemu-ios/bootrom",nand="/c/Users/nano/Downloads/qemu-ios/nand/",nor="/c/Users/nano/Downloads/qemu-ios/nor" -serial mon:stdio -cpu max -m 2G -d unimp -display sdl

error:

s5l8900_gpio_read: read from location 0x00000164
s5l8900_gpio_read: read from location 0x00000184
s5l8900_gpio_read: read from location 0x00000064
s5l8900_gpio_read: read from location 0x00000064
s5l8900_gpio_read: read from location 0x00000064
s5l8900_gpio_read: read from location 0x00000064
s5l8900_gpio_read: read from location 0x00000064
s5l8900_gpio_read: read from location 0x00000064
*** stack smashing detected ***: terminated

**Comment by devos50** [comment] 2024-01-01 16:02
@nanocodium thank you for reporting. I am not entirely sure if having quotes around the paths work in Windows and I provide the paths without quotes. The error log you provided, is there any other information before that?

**Comment by devos50** [comment] 2024-01-01 16:26
Seems to be a duplicate of #73, let's continue the discussion around this issue over there.

**Closed as completed by devos50** 2024-01-01 16:26 UTC
Labels: bug
